#!/usr/bin/env python3
"""Contract tests for explicit-domain composition, no actual App outputs."""
import unittest
import numpy as np
if __package__:
    from .pipeline import evaluate_hypothesis
    from .renderer import TextureLUT
else:
    from pipeline import evaluate_hypothesis
    from renderer import TextureLUT


def texel_center_identity(n=9):
    axis=(np.arange(n)+.5)/n
    b,g,r=np.meshgrid(axis,axis,axis,indexing='ij')
    return TextureLUT(np.stack([r,g,b],axis=-1),'center-identity')


def const(value,name='constant'):
    return TextureLUT(np.broadcast_to(value,(2,2,2,3)),name)


class PipelineTests(unittest.TestCase):
    def test_same_domain_analytic_identity_interior(self):
        rgb=np.random.default_rng(1199).uniform(.2,.8,(6,7,3))
        out,audit=evaluate_hypothesis(rgb,texel_center_identity(),input_space='srgb',lut_space='srgb',output_space='srgb')
        np.testing.assert_allclose(out,rgb,atol=2e-15)
        self.assertFalse(audit['clip_output']);self.assertEqual(audit['topology'],'single-tone')

    def test_explicit_cross_space_roundtrip_interior(self):
        rgb=np.random.default_rng(201).uniform(.3,.7,(100,3))
        out,audit=evaluate_hypothesis(rgb,texel_center_identity(17),input_space='srgb',lut_space='display-p3',output_space='srgb')
        np.testing.assert_allclose(out,rgb,atol=1e-14)
        self.assertEqual(audit['lut_space'],'display-p3')

    def test_fixed_known_p3_red_output_and_explicit_clip(self):
        table=const([1,0,0],'p3-red')
        opts=dict(input_space='srgb',lut_space='display-p3',output_space='srgb')
        out,audit=evaluate_hypothesis([[.5,.5,.5]],table,**opts)
        # Fixed standard vector, not generated by the conversion under test.
        np.testing.assert_allclose(out,[[1.0930663624351615,-.2267419735697543,-.1501345809371195]],atol=1e-14)
        self.assertEqual(audit['ranges']['output_before_clip']['outside_unit_rgb_pixels'],1)
        clipped,record=evaluate_hypothesis([[.5,.5,.5]],table,clip_output=True,**opts)
        np.testing.assert_array_equal(clipped,[[1,0,0]])
        self.assertEqual(record['ranges']['output_before_clip']['outside_unit_rgb_pixels'],1)
        self.assertEqual(record['ranges']['output_after_clip']['outside_unit_rgb_pixels'],0)

    def test_double_table_extrapolation_is_reported_not_silently_clipped(self):
        opts=dict(input_space='srgb-linear',lut_space='srgb-linear',output_space='srgb-linear',
                  secondary=const([0,0,0],'low'),blend_factor=2)
        out,audit=evaluate_hypothesis([[.5,.5,.5]],const([1,1,1],'high'),**opts)
        np.testing.assert_array_equal(out,[[2,2,2]])
        self.assertEqual(audit['ranges']['at_lut_output']['outside_unit_rgb_pixels'],1)
        self.assertEqual(audit['secondary_table'],'low')

    def test_filter_order_and_same_coordinate_to_two_tables(self):
        filter_lut=const([.3,.4,.5],'filter')
        primary=texel_center_identity(9)
        out,audit=evaluate_hypothesis([[.7,.2,.9]],primary,secondary=const([.1,.1,.1],'low'),blend_factor=.25,color_filter=filter_lut,
                                     input_space='srgb',lut_space='srgb',output_space='srgb')
        np.testing.assert_allclose(out,[[.15,.175,.2]],atol=2e-15)
        self.assertEqual(audit['topology'],'filtered-double-tone')
        self.assertEqual(audit['color_filter_table'],'filter')

    def test_transfer_must_be_explicit(self):
        table=const([.18,.18,.18])
        encoded,_=evaluate_hypothesis([[.5,.5,.5]],table,input_space='srgb',lut_space='srgb-linear',output_space='srgb')
        raw,_=evaluate_hypothesis([[.5,.5,.5]],table,input_space='srgb',lut_space='srgb',output_space='srgb')
        np.testing.assert_allclose(encoded,[[.46135612950044164]*3],atol=1e-14)
        np.testing.assert_allclose(raw,[[.18]*3],atol=1e-15)
        self.assertGreater(float(np.max(np.abs(encoded-raw))),.28)

    def test_ranges_expose_out_of_lut_cube(self):
        _,audit=evaluate_hypothesis([[1,0,0]],texel_center_identity(),input_space='display-p3',lut_space='srgb',output_space='srgb')
        self.assertEqual(audit['ranges']['at_lut_input']['outside_unit_rgb_pixels'],1)
        self.assertIn('Actual host color conversion location',audit['not_claimed'])

    def test_empty_shape_and_input_unchanged(self):
        x=np.empty((2,0,3));out,audit=evaluate_hypothesis(x,texel_center_identity(),input_space='srgb',lut_space='srgb',output_space='srgb')
        self.assertEqual(out.shape,x.shape);self.assertEqual(audit['ranges']['at_lut_input']['pixels'],0)
        x=np.array([[.2,.3,.4]]);copy=x.copy()
        evaluate_hypothesis(x,texel_center_identity(),input_space='srgb',lut_space='display-p3',output_space='srgb')
        np.testing.assert_array_equal(x,copy)

    def test_unknown_or_implicit_domain_not_accepted(self):
        with self.assertRaises(TypeError):evaluate_hypothesis([[.5,.5,.5]],texel_center_identity())
        with self.assertRaises(ValueError):evaluate_hypothesis([[.5,.5,.5]],texel_center_identity(),input_space='DP3',lut_space='srgb',output_space='srgb')
        with self.assertRaises(ValueError):evaluate_hypothesis([[.5,.5,.5]],texel_center_identity(),input_space='srgb',lut_space='srgb',output_space='srgb',clip_output='true')

if __name__=='__main__':unittest.main(verbosity=2)
